def Stats():
    #! hard output for statistics related to scheduling systems
    with open('simout.txt', 'w') as f:
        f.writelines("Algorithm FCFS\n")
        f.writelines("-- average CPU burst time: 0.000 ms\n")
        f.writelines("-- average wait time: 0.000 ms\n")
        f.writelines("-- average turnaround time: 0.000 ms\n")
        f.writelines("-- total number of context switches: 0\n")
        f.writelines("-- total number of preemptions: 0\n")
        f.writelines("-- CPU utilization: 0.000%\n")
        f.writelines("Algorithm SJF\n")
        f.writelines("-- average CPU burst time: 0.000 ms\n")
        f.writelines("-- average wait time: 0.000 ms\n")
        f.writelines("-- average turnaround time: 0.000 ms\n")
        f.writelines("-- total number of context switches: 0\n")
        f.writelines("-- total number of preemptions: 0\n")
        f.writelines("-- CPU utilization: 0.000%\n")
        f.writelines("Algorithm SRT\n")
        f.writelines("-- average CPU burst time: 0.000 ms\n")
        f.writelines("-- average wait time: 0.000 ms\n")
        f.writelines("-- average turnaround time: 0.000 ms\n")
        f.writelines("-- total number of context switches: 0\n")
        f.writelines("-- total number of preemptions: 0\n")
        f.writelines("-- CPU utilization: 0.000%\n")
        f.writelines("Algorithm RR\n")
        f.writelines("-- average CPU burst time: 0.000 ms\n")
        f.writelines("-- average wait time: 0.000 ms\n")
        f.writelines("-- average turnaround time: 0.000 ms\n")
        f.writelines("-- total number of context switches: 0\n")
        f.writelines("-- total number of preemptions: 0\n")
        f.writelines("-- CPU utilization: 0.000%\n")     